In [13]:
import torch


In [14]:
print(torch.__version__)

2.2.1+cu121


In [15]:
x=torch.rand(5,3)
x

tensor([[0.0936, 0.8353, 0.3733],
        [0.7007, 0.9393, 0.9505],
        [0.3446, 0.1046, 0.6134],
        [0.4693, 0.3287, 0.3419],
        [0.2823, 0.7879, 0.5190]])

In [16]:
y=torch.ones(5,3)
y

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [17]:
z=x+y
z

tensor([[1.0936, 1.8353, 1.3733],
        [1.7007, 1.9393, 1.9505],
        [1.3446, 1.1046, 1.6134],
        [1.4693, 1.3287, 1.3419],
        [1.2823, 1.7879, 1.5190]])

In [18]:
q=x.mm(y.t())
q

tensor([[1.3023, 1.3023, 1.3023, 1.3023, 1.3023],
        [2.5905, 2.5905, 2.5905, 2.5905, 2.5905],
        [1.0626, 1.0626, 1.0626, 1.0626, 1.0626],
        [1.1399, 1.1399, 1.1399, 1.1399, 1.1399],
        [1.5893, 1.5893, 1.5893, 1.5893, 1.5893]])

In [19]:
import numpy as np
a=np.ones([5,3])
b=torch.from_numpy(a)
b

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [20]:
c=torch.FloatTensor(a)
c

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [21]:
b.numpy()

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
if torch.cuda. is_available():
    x=x.cuda()
    y=y.cuda()
    z=x+y
print(z.cpu())

tensor([[1.0936, 1.8353, 1.3733],
        [1.7007, 1.9393, 1.9505],
        [1.3446, 1.1046, 1.6134],
        [1.4693, 1.3287, 1.3419],
        [1.2823, 1.7879, 1.5190]])


In [23]:
from torch.autograd import Variable
x=Variable(torch.ones(2,2),requires_grad=1)
x
y=x+2
y.grad_fn
z=torch.mean(y*y)
z.data
z.backward()
print(z.grad)
print(y.grad)
print(x.grad)

None
None
tensor([[1.5000, 1.5000],
        [1.5000, 1.5000]])


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_11408\3716767181.py:9: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten\src\ATen/core/TensorBody.h:494.)
  print(z.grad)
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_11408\3716767181.py:10: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Ten

In [24]:
s=Variable(torch.FloatTensor([[0.01,0.02]]),requires_grad=True)
x=Variable(torch.ones(2,2),requires_grad=True)
for i in range(10):
    s=s.mm(x)
z=torch.mean(s)
z.backward()
print(x.grad)
print(s.grad)

tensor([[37.1200, 37.1200],
        [39.6800, 39.6800]])
None


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_11408\3825299883.py:8: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten\src\ATen/core/TensorBody.h:494.)
  print(s.grad)
